services:
  billingextractor:
    build: .
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - LLM__Provider=${LLM__Provider}
      - LLM__Model=${LLM__Model}
      - Gemini__ApiKey=${GEMINI_API_KEY}
      - Gemini__ProjectId=${GEMINI_PROJECT_ID}
      - Gemini__Location=${GEMINI_LOCATION}
      - Gemini__ModelId=${GEMINI__MODELID}
    volumes:
      - ./FileStorage:/app/FileStorage
      - billingextractor-data:/app/data

volumes:
  billingextractor-data: